config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :friends
  resources :users, only: [:show]
  resources :tweets, except: [:edit, :update]

  get '/followers', to: 'home#followers'
  get 'users', to: 'home#users'

  get "up" => "rails/health#show", as: :rails_health_check

  get 'home/index'

  post 'follow/:id', to: 'home#follow', as: 'follow_user'
  delete 'unfollow/:id', to: 'home#unfollow', as: 'unfollow_user'

  root to: "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :followee, foreign_key: :followed_id, class_name: "User"

  belongs_to :follower, foreign_key: :follower_id, class_name: "User"
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :body, presence: true, length: { maximum: 280 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :favorites

  has_many :followed_users, foreign_key: :follower_id, class_name: "Following"
  has_many :followees, through: :followed_users, source: :followee

  has_many :follower_users, foreign_key: :followee_id, class_name: "Following"
  has_many :followers, through: :follower_users, source: :follower


  def follows?(other_user)
    self.followees.include?(other_user)
  end

  def follow(other_user)
    self.followees << other_user unless self.follows?(other_user)
  end

  def unfollow(other_user)
    self.followees.delete(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def users
    @users = User.all
  end

  def follow
    user = User.find(params[:id])
    current_user.follow(user)
    redirect_to users_path
  end

  def unfollow
    user = User.find(params[:id])
    current_user.unfollow(user)
    redirect_to users_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweet = Tweet.new
    @tweets = Tweet.all.order(created_at: :desc)
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    respond_to do |format|
      if @tweet.save
      format.html { redirect_to tweets_path, notice: 'Tweet was successfully created.' }
      else
        format.html do
          flash.now[:alert] = 'Failed to create tweet.'
          render :new
        end
      end
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    redirect_to tweets_path
  end

  private

    def tweet_params
      params.require(:tweet).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end
def index
  # din kod här
end

def show
  # din kod här
end

# andra actions...

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>User:</strong>
    <%= friend.user_id %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends</h1>

<div id="friends">
  <% @friends.each do |friend| %>
    <%= render friend %>
    <p>
      <%= link_to "Show this friend", friend %>
    </p>
  <% end %>
</div>

<%= link_to "New friend", new_friend_path %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend) %> |
  <%= link_to "Back to friends", friends_path %>

  <%= button_to "Destroy this friend", @friend, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Twittercopy', root_path, class: "navbar-brand" %>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
               
        <% if user_signed_in? %>
         <li class="nav-item">
          <%= link_to 'All users', '/followers', class: "nav-link" %>
            </li>
          <li class="nav-item">
          <%= link_to 'edit profile', edit_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>

          </li>
          <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>

      </ul>
    
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/users.html.erb
<h1>All users</h1>
<p>a list with all users</p>

<table id="users" class="table">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Handle</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
            <td><%= user.name %></td>
            <td> <%= user.email %></td>
            <td><%= link_to "Show", user_path(user) %></td>
            <% if current_user.follows?(user) %>
                <td><%= button_to 'Unfollow', unfollow_user_path(user), method: :delete %></td>
            <% else %>
                <td><%= button_to 'Follow', follow_user_path(user), method: :post %></td>
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends app</title>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <%= render 'home/header' %>

    <div class="container">
    <br/>
    
      <br/>
      <%= yield %>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tweets/index.html.erb
<%= form_with model: @tweet do |form| %>
    <% if form.object.errors.any? %>
        <div>
            <h2><%= pluralize(form.object.errors.count, "error") %> prophibited this Tweet from being saved:</h2>
            <ul>
                <% form.object.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        
        </div>
    <% end %>

    <%= form.text_area :body, placeholder: "Whats on your mind?" %>

    <div> 
       <%= form.submit "Tweet" %> 
    </div>

   
<% end %>
  <div>
        <br />
        <h2>All Tweets:</h2>
        <% @tweets.each do |tweet| %>
           <div>
            <br/>
                <%= tweet.body %> 
                <br/>
                <%= tweet.user.email %> 
              
                <%= tweet.updated_at.in_time_zone("Stockholm").strftime("%H.%M %e %B -%y") %>
                <%= button_to 'Delete', tweet_path(tweet), method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
           
        <% end %>
    </div>

app/views/tweets/new.html.erb
<%= form_with model: @tweet do |form| %>
  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(form.object.errors.count, "error") %> prohibited this tweet from being saved:</h2>
      <ul>
        <% form.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :body, "Tweet content:" %>
    <%= form.text_area :body, class: "form-control", placeholder: "What's on your mind?" %>
  </div>

  <div class="form-group">
    <%= form.submit "Create Tweet", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Back to Tweets", tweets_path %>